const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET,POST,PATCH,DELETE,OPTIONS"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"Content-Type":"application/json",...cors}});
async function hashPassword(password,salt){const enc=new TextEncoder();const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},key,256);return [...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function b64(a){return btoa(String.fromCharCode(...a))}
async function passwordRecord(p){const salt=crypto.getRandomValues(new Uint8Array(16));return b64(salt)+"$"+await hashPassword(p,salt)}
async function verify(p,record){const [s,h]=record.split("$");const salt=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return h===await hashPassword(p,salt)}
async function tokenHash(t){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function current(request,env){const c=request.headers.get("Cookie")||"";const m=c.match(/cec_session=([^;]+)/);if(!m)return null;const h=await tokenHash(m[1]);return await env.DB.prepare("SELECT u.id,u.username,u.role,u.team,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.active=1").bind(h).first()}
function setCookie(v,max=2592000){return "cec_session="+v+"; Max-Age="+max+"; Path=/; HttpOnly; Secure; SameSite=None"}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:cors});const u=new URL(request.url);try{
if(u.pathname==="/api/login"&&request.method==="POST"){const {username,password}=await request.json();const user=await env.DB.prepare("SELECT * FROM users WHERE username=?").bind(username).first();if(!user||!user.active||!(await verify(password,user.password_hash)))return json({error:"invalid_credentials"},401);const token=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+30 days'))").bind(await tokenHash(token),user.id).run();return new Response(JSON.stringify({user:{username:user.username,role:user.role,team:user.team}}),{headers:{"Content-Type":"application/json","Set-Cookie":setCookie(token),...cors}})}
if(u.pathname==="/api/logout"&&request.method==="POST"){const user=await current(request,env);if(user){const c=request.headers.get("Cookie")||"",m=c.match(/cec_session=([^;]+)/);if(m)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await tokenHash(m[1])).run()}return new Response(JSON.stringify({ok:true}),{headers:{"Content-Type":"application/json","Set-Cookie:setCookie("",0),...cors}})}
if(u.pathname==="/api/me"&&request.method==="GET"){const user=await current(request,env);if(!user)return json({error:"unauthorized"},401);return json({user})}
const user=await current(request,env);if(!user||user.role!=="admin")return json({error:"forbidden"},403);
if(u.pathname==="/api/users"&&request.method==="GET"){const r=await env.DB.prepare("SELECT id,username,role,team,active,created_at FROM users ORDER BY username").all();return json({users:r.results})}
if(u.pathname==="/api/users"&&request.method==="POST"){const {username,password,role,team}=await request.json();if(!username||!password||!role)return json({error:"missing_fields"},400);const ph=await passwordRecord(password);try{await env.DB.prepare("INSERT INTO users(username,password_hash,role,team,active,created_at) VALUES(?,?,?,?,1,datetime('now'))").bind(username,ph,role,team||null).run()}catch{return json({error:"username_exists"},409)}return json({ok:true})}
if(u.pathname.startsWith("/api/users/")&&request.method==="DELETE"){const id=u.pathname.split("/").pop();await env.DB.prepare("UPDATE users SET active=0 WHERE id=?").bind(id).run();return json({ok:true})}
return json({error:"not_found"},404)}catch(e){return json({error:"server_error",detail:e.message},500)}}}