const teams=[
 ["conception","🧩 Conception","Choix techniques et architecture",65],
 ["modelisation-3D","🧱 Modélisation 3D","Modèles, plans et versions",40],
 ["materiaux","🧪 Matériaux","Matériaux et justification",80],
 ["fabrication","🛠️ Fabrication","Impression et fabrication",30],
 ["assemblage","🔩 Assemblage","Montage et intégration",0],
 ["essais","🏁 Essais","Mesures et validation",0],
 ["presentation","🎤 Présentation","Oral et communication",0]
];
const types={journal:{label:"Journal",icon:"📅",list:"journalList"},problem:{label:"Problèmes",icon:"⚠️",list:"problemList"},idea:{label:"Idées",icon:"💡",list:"ideaList"},test:{label:"Tests",icon:"🧪",list:"testList"}};
let me=null,progressState={},currentPage="accueil",teamView=null,teamTab="annotations",sketchDirty=false;
const $=id=>document.getElementById(id);
async function api(path,opt={}){if(!window.CEC_AUTH_API)throw new Error("Serveur de connexion non configuré");const r=await fetch(window.CEC_AUTH_API+"/api"+path,{credentials:"include",headers:{"Content-Type":"application/json"},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.error||"Erreur serveur");return d}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function roleName(){return me.role==="admin"?"👑 Administrateur":me.role==="prof"?"👨‍🏫 Professeur":me.is_leader?"⭐ Chef d’équipe":"👨‍🎓 Élève"}
function canEdit(){return me.role!=="prof"}
function percent(team){return progressState[team]??(teams.find(t=>t[0]===team)?.[3]??0)}
function teamName(id){return teams.find(t=>t[0]===id)?.[1]||"Équipe non attribuée"}
function flash(el,message,ok=false){if(!el)return;el.textContent=message;el.className=ok?"success":"error";el.hidden=false}
function progressRows(editable=false){return teams.map(t=>{const p=percent(t[0]);return '<div class="progressrow"><div class="progresshead"><span>'+t[1]+'</span><strong id="pct-'+t[0]+'">'+p+' %</strong></div><div class="bar"><div class="fill" style="width:'+p+'%"></div></div>'+(editable?'<input class="progress-slider" aria-label="Progression '+esc(t[1])+'" type="range" min="0" max="100" value="'+p+'" data-team="'+t[0]+'" '+(!canEdit()?'disabled':'')+'><div class="slider-foot"><span>0 %</span><span>Déplace le point pour actualiser</span><span>100 %</span></div>':'')+'</div>'}).join("")}
function shell(page,title,body){currentPage=page;$("page").innerHTML='<div class="hero"><div><span class="eyebrow">ESPACE PROJET</span><h2>'+title+'</h2></div></div>'+body;document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===page))}
function topIdentity(){const own=teams.find(t=>t[0]===me.team);$("identity").textContent=roleName()+" · "+me.username+(own?" · "+own[1]:"")}
function start(){if(me.role!=="prof"&&!me.team){$("appView").hidden=true;showTeamPicker();return} $("loginView").hidden=true;$("teamPicker").hidden=true;$("appView").hidden=false;$("adminNav").hidden=me.role!=="admin";$("leaderNav").hidden=!me.is_leader;$("profileBtn").hidden=false;document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>render(b.dataset.page));topIdentity();render("accueil")}
function showLogin(){$("appView").hidden=true;$("teamPicker").hidden=true;$("loginView").hidden=false;window.scrollTo(0,0)}
function showTeamPicker(){$("loginView").hidden=true;$("appView").hidden=true;$("teamPicker").hidden=false;$("teamPicker").innerHTML='<div class="team-picker-card"><span class="eyebrow">PREMIÈRE CONNEXION</span><h1>Choisis ton équipe</h1><div class="warning-red">⚠️ ATTENTION — CE CHOIX EST DÉFINITIF. Tu ne pourras pas le modifier toi-même après validation. Seul l’administrateur pourra le changer.</div><p>Ce choix permet de classer automatiquement tes annotations, idées, problèmes et tests dans le bon espace d’équipe.</p><form id="teamChoiceForm" class="form-grid"><label>Mon équipe<select name="team" required><option value="">Choisir une équipe…</option>'+teams.map(t=>'<option value="'+t[0]+'">'+t[1]+'</option>').join("")+'</select></label><button class="button primary" type="submit">Confirmer définitivement mon équipe</button><p id="teamChoiceMsg" hidden></p></form></div>';window.scrollTo(0,0)}
async function boot(){try{const d=await api("/me");me=d.user;start()}catch{showLogin()}}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").hidden=true;const btn=$("loginForm").querySelector("button");btn.disabled=true;btn.textContent="Connexion…";try{const d=await api("/login",{method:"POST",body:JSON.stringify({username:$("username").value.trim(),password:$("password").value})});me=d.user;start();window.scrollTo(0,0)}catch(err){$("loginError").textContent=err.message==="invalid_credentials"?"Identifiant ou mot de passe incorrect.":err.message;$("loginError").hidden=false}finally{btn.disabled=false;btn.textContent="Se connecter"}};
$("logoutBtn").onclick=async()=>{try{await api("/logout",{method:"POST"})}catch{}me=null;showLogin()};
$("profileBtn").onclick=()=>render("profil");
document.addEventListener("submit",async e=>{
 if(e.target.id==="teamChoiceForm"){e.preventDefault();const msg=$("teamChoiceMsg"),team=new FormData(e.target).get("team");try{await api("/team/select",{method:"POST",body:JSON.stringify({team})});me.team=team;start()}catch(err){flash(msg,err.message)}return}
 if(e.target.id==="profileForm"){e.preventDefault();if(!canEdit())return;const f=e.target,msg=$("profileMsg"),username=f.elements.username.value.trim(),password=f.elements.password.value;try{const d=await api("/profile",{method:"POST",body:JSON.stringify({username,password:password||undefined})});me={...me,...d.user};topIdentity();flash(msg,"Profil mis à jour.",true);f.elements.password.value=""}catch(err){flash(msg,err.message)}return}
 if(e.target.id==="annotationForm"){e.preventDefault();if(!canEdit())return;const f=e.target,msg=$("annotationMsg");try{const photos=await readPhotos(f.elements.photos.files);const title=f.elements.title.value.trim(),content=f.elements.content.value.trim();await api("/annotations",{method:"POST",body:JSON.stringify({content:title+"\n"+content,photos})});f.reset();flash(msg,"Annotation publiée dans "+teamName(me.team)+".",true);loadAnnotations()}catch(err){flash(msg,err.message)}return}
 if(e.target.matches(".item-form")){e.preventDefault();if(!canEdit())return;const f=e.target,msg=f.querySelector(".form-message"),data=Object.fromEntries(new FormData(f));try{data.photos=await readPhotos(f.elements.photos?.files);data.type=f.dataset.type;await api("/items",{method:"POST",body:JSON.stringify(data)});f.reset();flash(msg,"Enregistré dans "+teamName(me.team)+".",true);loadItems(data.type,types[data.type].list)}catch(err){flash(msg,err.message)}return}
 if(e.target.id==="privateNoteForm"){e.preventDefault();const f=e.target,msg=$("privateNoteMsg");try{const photos=await readPhotos(f.elements.photos.files);if(sketchDirty){photos.push({filename:"schema-dessine.png",mime_type:"image/png",data_url:$("sketchCanvas").toDataURL("image/png")})}await api("/private-notes",{method:"POST",body:JSON.stringify({title:f.elements.title.value,content:f.elements.content.value,photos})});f.reset();clearSketch();flash(msg,"Note enregistrée dans ton espace privé.",true);loadPrivateNotes()}catch(err){flash(msg,err.message)}return}
 if(e.target.id==="createUser"){e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),msg=$("adminMsg");try{await api("/users",{method:"POST",body:JSON.stringify(d)});f.reset();flash(msg,"Compte créé.",true);loadUsers()}catch(err){flash(msg,err.message)}}
});
document.addEventListener("input",e=>{if(!e.target.matches(".progress-slider"))return;const t=e.target.dataset.team,p=Number(e.target.value),row=e.target.closest(".progressrow");row.querySelector(".fill").style.width=p+"%";$("pct-"+t).textContent=p+" %"});
document.addEventListener("change",async e=>{if(!e.target.matches(".progress-slider"))return;const input=e.target;try{await api("/progress",{method:"POST",body:JSON.stringify({team:input.dataset.team,percent:Number(input.value)})});progressState[input.dataset.team]=Number(input.value)}catch(err){alert("Impossible d’enregistrer : "+err.message);loadProgress()}});
function itemForm(type,heading,date=false,teamField=false){if(!canEdit())return '<div class="readonly-note">👁️ Mode consultation : le compte professeur ne peut pas modifier le projet.</div>';return '<div class="panel"><h3>'+heading+'</h3><form class="form-grid item-form" data-type="'+type+'"><label>Titre<input name="title" maxlength="140" required placeholder="Donne un titre clair"></label>'+(date?'<label>Date prévue (facultatif)<input name="session_date" type="date"></label>':'')+(teamField&&me.role==="admin"?'<label>Équipe<select name="team">'+teams.map(t=>'<option value="'+t[0]+'">'+t[1]+'</option>').join("")+'</select></label>':'')+'<label>Description<textarea name="content" maxlength="5000" required placeholder="Décris les informations utiles…"></textarea></label><label>Photos (4 maximum)<input name="photos" type="file" accept="image/*" multiple></label><button class="button" type="submit">Enregistrer</button><p class="form-message" hidden></p></form></div>'}
function render(page="accueil"){if(page!=="equipes")teamView=null;topIdentity();const own=teams.find(t=>t[0]===me.team);
 if(page==="accueil"){shell(page,"Bonjour "+esc(me.username)+" 👋",'<div class="hero welcome"><div><span class="eyebrow">'+roleName().toUpperCase()+'</span><h2>'+(own?own[1]:"Vue globale")+'</h2><p>Ton espace de travail Course en Cours.</p></div></div><div class="grid"><div class="metric"><b>🏎️ Course en Cours</b><small>Projet collectif</small></div><div class="metric"><b>📅 Journal</b><small>Séances du projet</small></div><div class="metric"><b>💬 Annotations</b><small>Suivi du groupe</small></div><div class="metric"><b>🧪 Tests</b><small>Essais et résultats</small></div></div><div class="panel"><h3>📈 Progression globale</h3>'+progressRows(false)+'</div>')}
 else if(page==="progression"){shell(page,"📊 Progression du projet",'<div class="panel"><p class="muted">Déplace le curseur pour indiquer l’avancement estimé. Les valeurs sont partagées avec les autres utilisateurs.</p><div id="progressMessage" hidden></div>'+progressRows(true)+'</div>');loadProgress()}
 else if(page==="equipes"){shell(page,"👥 Les équipes",'<p class="muted">Ouvre une équipe pour consulter ses membres et ses travaux. Les équipes peuvent consulter les autres espaces, mais leurs publications restent classées dans leur équipe.</p><div class="team-list" id="teamList">Chargement…</div>');loadTeams()}
 else if(page==="journal"){shell(page,"📅 Journal des séances",itemForm("journal","Ajouter une séance",true)+'<div class="panel"><h3>Prochaines séances et historique</h3><div id="journalList" class="item-list">Chargement…</div></div>');loadItems("journal","journalList")}
 else if(page==="annotations"){shell(page,"💬 Annotations",(canEdit()?'<div class="panel"><h3>Nouvelle annotation · '+esc(teamName(me.team))+'</h3><form id="annotationForm" class="form-grid"><label>Titre<input name="title" maxlength="140" required placeholder="Ex. Choix du matériau du châssis"></label><label>Annotation<textarea name="content" maxlength="2000" required placeholder="Décris ta remarque, une décision ou une question…"></textarea></label><label>Photos (4 maximum)<input name="photos" type="file" accept="image/*" multiple></label><button class="button" type="submit">Publier l’annotation</button><p id="annotationMsg" hidden></p></form></div>':'<div class="readonly-note">👁️ Mode consultation : le professeur peut lire les annotations, mais pas en ajouter.')+'<div class="panel"><h3>Toutes les annotations par équipe</h3><div id="annotationList" class="item-list">Chargement…</div></div>');loadAnnotations()}
 else if(page==="problemes"||page==="idees"||page==="tests"){const type=page==="problemes"?"problem":page==="idees"?"idea":"test",t=types[type];shell(page,t.icon+" "+t.label,itemForm(type,type==="problem"?"Signaler un problème":type==="idea"?"Proposer une idée":"Ajouter un test")+'<div class="panel"><h3>'+t.label+' — toutes les équipes</h3><div id="'+t.list+'" class="item-list">Chargement…</div></div>');loadItems(type,t.list)}
 else if(page==="profil"){shell(page,"👤 Mon profil",'<div class="panel"><h3>Informations du compte</h3>'+(canEdit()?'<form id="profileForm" class="form-grid"><label>Identifiant<input name="username" value="'+esc(me.username)+'" minlength="3" maxlength="40" required></label><label>Nouveau mot de passe <small>(laisser vide pour ne pas le changer)</small><input name="password" type="password" minlength="8" autocomplete="new-password" placeholder="Au moins 8 caractères"></label><label>Rôle<input value="'+esc(roleName())+'" disabled></label><label>Équipe<input value="'+esc(teamName(me.team))+'" disabled></label><p class="muted">Le rôle et l’équipe ne peuvent pas être modifiés depuis ton profil.</p><button class="button" type="submit">Enregistrer les changements</button><p id="profileMsg" hidden></p></form>':'<div class="form-grid"><p>Identifiant : <b>'+esc(me.username)+'</b></p><p>Rôle : '+esc(roleName())+'</p><p>Équipe : '+esc(teamName(me.team))+'</p><p class="readonly-note">Le profil professeur est en lecture seule.</p></div>')+'</div>')}
 else if(page==="chef"){if(!me.is_leader){render("accueil");return}shell(page,"⭐ Espace privé du chef d’équipe",'<div class="private-banner">🔒 Espace strictement privé : tes notes, photos et schémas ne sont visibles que par toi, pas par les autres élèves ni le professeur.</div><div class="panel"><h3>Nouvelle note privée</h3><form id="privateNoteForm" class="form-grid"><label>Titre<input name="title" maxlength="140" required></label><label>Notes<textarea name="content" maxlength="5000" required placeholder="Plan d’action, idées à organiser, notes personnelles…"></textarea></label><label>Photos (4 maximum)<input name="photos" type="file" accept="image/*" multiple></label><div><b>Schéma personnel</b><p class="muted">Dessine directement dans la zone, puis enregistre la note.</p><canvas id="sketchCanvas" width="900" height="260"></canvas><button class="button secondary" type="button" id="clearSketch">Effacer le schéma</button></div><button class="button" type="submit">Enregistrer dans mon espace privé</button><p id="privateNoteMsg" hidden></p></form></div><div class="panel"><h3>Mes notes privées</h3><div id="privateNotes" class="item-list">Chargement…</div></div>');initSketch();loadPrivateNotes()}
 else if(page==="admin"){if(me.role!=="admin")return render("accueil");shell(page,"⚙️ Administration",'<div class="admin-grid"><div class="panel"><h3>Créer un compte</h3><form id="createUser" class="form-grid"><label>Identifiant<input name="username" required></label><label>Mot de passe<input name="password" type="password" minlength="8" required></label><label>Rôle<select name="role"><option value="eleve">Élève</option><option value="prof">Professeur (lecture seule)</option><option value="admin">Administrateur</option></select></label><label>Équipe<select name="team"><option value="">À choisir à la première connexion</option>'+teams.map(t=>'<option value="'+t[0]+'">'+t[1]+'</option>').join("")+'</select></label><button class="button" type="submit">Créer le compte</button><p id="adminMsg" hidden></p></form></div><div class="panel"><h3>Comptes, équipes et responsables</h3><p class="muted">L’administrateur peut changer les équipes et désigner un chef d’équipe.</p><div id="users" class="user-list">Chargement…</div></div></div>');loadUsers()}
}
async function readPhotos(files){const arr=[];for(const file of Array.from(files||[]).slice(0,4)){if(!file.type.startsWith("image/"))continue;const data=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{const scale=Math.min(1,1200/im.width,1200/im.height),canvas=document.createElement("canvas");canvas.width=Math.round(im.width*scale);canvas.height=Math.round(im.height*scale);canvas.getContext("2d").drawImage(im,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.68))};im.onerror=reject;im.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)});if(data.length<850000)arr.push({filename:file.name,mime_type:"image/jpeg",data_url:data})}return arr}
async function loadProgress(){try{const d=await api("/progress");d.progress.forEach(p=>{progressState[p.team]=p.percent;const input=document.querySelector('.progress-slider[data-team="'+p.team+'"]');if(input){input.value=p.percent;input.closest(".progressrow").querySelector(".fill").style.width=p.percent+"%";$("pct-"+p.team).textContent=p.percent+" %"}})}catch(e){}}
async function loadTeams(){try{const d=await api("/teams");d.progress.forEach(p=>progressState[p.team]=p.percent);$("teamList").innerHTML=teams.map(t=>{const members=d.users.filter(u=>u.team===t[0]);return '<details class="team-card"><summary><span>'+t[1]+'</span><span class="muted">'+members.length+' membre(s)</span><span class="badge">'+percent(t[0])+' %</span></summary><p>'+t[2]+'</p><div class="member-list">'+(members.length?members.map(m=>'<div class="member"><b>'+esc(m.username)+(m.is_leader?' ⭐':'')+'</b><span>'+(m.role==="prof"?"Professeur":m.role==="admin"?"Administrateur":m.is_leader?"Chef d’équipe":"Élève")+'</span><small>Mission : '+esc(t[2])+'</small></div>').join(""):'<p class="muted">Aucun membre affecté.</p>')+'</div><div class="team-subtabs">'+["annotations","problem","idea","test","journal"].map(tab=>'<button class="button secondary" data-team-open="'+t[0]+'" data-team-tab="'+tab+'">'+(tab==="annotations"?"💬 Annotations":types[tab]?.icon+" "+(types[tab]?.label||"Journal"))+'</button>').join("")+'</div></details>'}).join("")}catch(e){$("teamList").textContent="Impossible de charger : "+e.message}}
async function loadItems(type,target){try{const d=await api("/items?type="+encodeURIComponent(type)),el=$(target);if(!d.items.length){el.innerHTML='<p class="notice">Aucun élément pour le moment.</p>';return}el.innerHTML=d.items.map(i=>'<button class="item-card" data-item-id="'+i.id+'" data-item-type="'+type+'"><span class="item-title">'+esc(i.title)+'</span><span class="item-meta">'+esc(teamName(i.team))+' · '+esc(i.username)+' · '+new Date(i.created_at+"Z").toLocaleDateString("fr-FR")+'</span><span class="item-preview">'+esc(i.content.slice(0,130))+(i.content.length>130?"…":"")+'</span>'+(i.photos?.length?'<span class="photo-count">📷 '+i.photos.length+' photo(s)</span>':'')+'<span class="item-open">Ouvrir le détail →</span></button>').join("")}catch(e){$(target).textContent="Impossible de charger : "+e.message}}
async function loadAnnotations(){try{const d=await api("/annotations"),el=$("annotationList");if(!d.annotations.length){el.innerHTML='<p class="notice">Aucune annotation pour le moment.</p>';return}el.innerHTML=d.annotations.map(a=>{const parts=a.content.split("\n"),title=parts.shift()||"Annotation sans titre";return '<button class="item-card" data-annotation-id="'+a.id+'"><span class="item-title">'+esc(title)+'</span><span class="item-meta">'+esc(teamName(a.team))+' · '+esc(a.username)+' · '+new Date(a.created_at+"Z").toLocaleString("fr-FR")+'</span><span class="item-preview">'+esc(parts.join(" ").slice(0,140))+'</span>'+(a.photos?.length?'<span class="photo-count">📷 '+a.photos.length+' photo(s)</span>':'')+'<span class="item-open">Ouvrir l’annotation →</span></button>'}).join("")}catch(e){$("annotationList").textContent="Impossible de charger : "+e.message}}
async function openTeamTab(team,tab){teamView=team;teamTab=tab;const label=tab==="annotations"?"Annotations":types[tab]?.label||"Journal";shell("equipes",teamName(team)+' — '+label,'<div class="panel"><button class="button secondary" id="backTeams">← Retour aux équipes</button><h3>'+label+' de '+esc(teamName(team))+'</h3><div id="teamContent" class="item-list">Chargement…</div></div>');$("backTeams").onclick=()=>render("equipes");try{if(tab==="annotations"){const d=await api("/annotations"),items=d.annotations.filter(a=>a.team===team);renderTeamCards(items,"annotation")}else{const d=await api("/items?type="+encodeURIComponent(tab)),items=d.items.filter(i=>i.team===team);renderTeamCards(items,tab)}}catch(e){$("teamContent").textContent=e.message}}
function renderTeamCards(items,type){const el=$("teamContent");if(!items.length){el.innerHTML='<p class="notice">Cette équipe n’a pas encore publié de contenu dans cette rubrique.</p>';return}el.innerHTML=items.map(i=>'<button class="item-card" '+(type==="annotation"?'data-annotation-id="'+i.id+'"':'data-item-id="'+i.id+'" data-item-type="'+type+'"')+'><span class="item-title">'+esc(type==="annotation"?(i.content.split("\n")[0]||"Annotation"):i.title)+'</span><span class="item-meta">'+esc(i.username)+' · '+new Date(i.created_at+"Z").toLocaleDateString("fr-FR")+'</span><span class="item-preview">'+esc((type==="annotation"?i.content.split("\n").slice(1).join(" "):i.content).slice(0,140))+'</span>'+(i.photos?.length?'<span class="photo-count">📷 '+i.photos.length+' photo(s)</span>':'')+'<span class="item-open">Ouvrir →</span></button>').join("")}
function photoGallery(photos){return photos?.length?'<div class="photo-gallery">'+photos.map(p=>'<a href="'+p.data_url+'" target="_blank" rel="noopener"><img src="'+p.data_url+'" alt="'+esc(p.filename)+'"></a>').join("")+'</div>':''}
document.addEventListener("click",async e=>{
 const teamBtn=e.target.closest("[data-team-open]");if(teamBtn){openTeamTab(teamBtn.dataset.teamOpen,teamBtn.dataset.teamTab);return}
 if(e.target.id==="clearSketch"){clearSketch();return}
 const ann=e.target.closest("[data-annotation-id]");if(ann){const d=await api("/annotations"),a=d.annotations.find(x=>String(x.id)===ann.dataset.annotationId);if(!a)return;const parts=a.content.split("\n"),title=parts.shift();shell("annotations","💬 "+esc(title),'<div class="panel detail-panel"><button class="button secondary" id="backToAnnotations">← Retour</button><p class="item-meta">'+esc(teamName(a.team))+' · '+esc(a.username)+' · '+new Date(a.created_at+"Z").toLocaleString("fr-FR")+'</p><div class="detail-content">'+esc(parts.join("\n")).replace(/\n/g,"<br>")+'</div>'+photoGallery(a.photos)+'</div>');$("backToAnnotations").onclick=()=>teamView?openTeamTab(teamView,teamTab):render("annotations");return}
 const item=e.target.closest("[data-item-id]");if(item){try{const d=await api("/items/"+item.dataset.itemId),i=d.item;const type=i.type,back=()=>teamView?openTeamTab(teamView,teamTab):render(type==="problem"?"problemes":type==="idea"?"idees":type==="test"?"tests":"journal");shell(type,types[type]?.icon+" "+esc(i.title),'<div class="panel detail-panel"><button class="button secondary" id="backToItems">← Retour</button><p class="item-meta">'+esc(teamName(i.team))+' · '+esc(i.username)+' · '+new Date(i.created_at+"Z").toLocaleString("fr-FR")+'</p><div class="detail-content">'+esc(i.content).replace(/\n/g,"<br>")+'</div>'+photoGallery(i.photos)+'</div>');$("backToItems").onclick=back}catch(err){alert("Impossible d’ouvrir : "+err.message)}return}
 const note=e.target.closest("[data-private-note]");if(note){const id=note.dataset.privateNote;const d=await api("/private-notes"),n=d.notes.find(x=>String(x.id)===id);if(!n)return;shell("chef","🔒 "+esc(n.title),'<div class="panel detail-panel"><button class="button secondary" id="backPrivate">← Retour à mes notes</button><div class="detail-content">'+esc(n.content).replace(/\n/g,"<br>")+'</div>'+photoGallery(n.photos)+'</div>');$("backPrivate").onclick=()=>render("chef")}
 const userAct=e.target.closest("[data-user-save]");if(userAct){const id=userAct.dataset.userSave,card=userAct.closest(".user-admin-card"),team=card.querySelector("[name=team]").value,role=card.querySelector("[name=role]").value,is_leader=card.querySelector("[name=is_leader]").checked;try{await api("/users/"+id,{method:"PATCH",body:JSON.stringify({team,role,is_leader})});flash(card.querySelector(".user-msg"),"Compte mis à jour.",true);loadUsers()}catch(err){flash(card.querySelector(".user-msg"),err.message)}}
});
async function loadUsers(){try{const d=await api("/users");$("users").innerHTML=d.users.map(u=>'<div class="user-admin-card"><b>'+esc(u.username)+'</b><div class="admin-controls"><label>Rôle<select name="role">'+["eleve","prof","admin"].map(r=>'<option value="'+r+'" '+(u.role===r?"selected":"")+'>'+({eleve:"Élève",prof:"Professeur",admin:"Administrateur"}[r])+'</option>').join("")+'</select></label><label>Équipe<select name="team"><option value="">Aucune / à choisir</option>'+teams.map(t=>'<option value="'+t[0]+'" '+(u.team===t[0]?"selected":"")+'>'+t[1]+'</option>').join("")+'</select></label><label class="leader-check"><input type="checkbox" name="is_leader" '+(u.is_leader?"checked":"")+'> Chef d’équipe</label></div><button class="button" data-user-save="'+u.id+'">Enregistrer</button><p class="user-msg" hidden></p></div>').join("")}catch(e){$("users").textContent=e.message}}
async function loadPrivateNotes(){try{const d=await api("/private-notes");$("privateNotes").innerHTML=d.notes.length?d.notes.map(n=>'<button class="item-card" data-private-note="'+n.id+'"><span class="item-title">'+esc(n.title)+'</span><span class="item-meta">'+new Date(n.updated_at+"Z").toLocaleString("fr-FR")+'</span><span class="item-preview">'+esc(n.content.slice(0,130))+'</span>'+(n.photos?.length?'<span class="photo-count">📷 / schémas : '+n.photos.length+'</span>':'')+'<span class="item-open">Ouvrir la note privée →</span></button>').join(""):'<p class="notice">Aucune note privée enregistrée.</p>'}catch(e){$("privateNotes").textContent=e.message}}
function initSketch(){const canvas=$("sketchCanvas");if(!canvas)return;const ctx=canvas.getContext("2d");ctx.lineWidth=3;ctx.lineCap="round";ctx.strokeStyle="#17202a";let drawing=false;const pos=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};canvas.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();sketchDirty=true};canvas.onpointerup=canvas.onpointercancel=()=>drawing=false;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);$("clearSketch").onclick=clearSketch}
function clearSketch(){const c=$("sketchCanvas");if(!c)return;const ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);sketchDirty=false}
boot();
